spring.application.name=renthub-backend

spring.profiles.active=dev

spring.jpa.open-in-view=false

spring.jackson.default-property-inclusion=non_null

server.error.include-message=always

server.error.include-binding-errors=always
# =========================
# JWT Configuration
# =========================

jwt.secret=RentHubAISecretKeyForJWTAuthentication2026VerySecureKey123456789
jwt.access-token-expiration=3600000
jwt.refresh-token-expiration=604800000