server.port=8081

spring.datasource.url=jdbc:postgresql://localhost:5432/renthub_test

spring.datasource.username=postgres

spring.datasource.password=vinay

spring.jpa.hibernate.ddl-auto=create-drop

spring.jpa.show-sql=false